# Generated by Django 2.1.5 on 2022-02-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.City')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.State')),
            ],
        ),
    ]
