# Generated by Django 2.1.5 on 2022-02-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0002_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='sid',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
