# Generated by Django 2.1.5 on 2022-02-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0003_auto_20220210_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(default='india', max_length=500)),
                ('status', models.CharField(default='inactive', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.MemberPost'),
        ),
    ]
