# Generated by Django 2.1.5 on 2022-02-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0005_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ctype', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('img', models.ImageField(default='', upload_to='campaign/')),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='org',
            name='doj',
            field=models.DateField(),
        ),
    ]
