# Generated by Django 2.1.5 on 2022-03-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0009_donations_razorpay_ordid'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='org',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
