# Generated by Django 2.1.5 on 2022-03-13 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0011_auto_20220313_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='datetime_of_payment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donations',
            name='ordid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
