# Generated by Django 2.1.5 on 2022-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0012_auto_20220313_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='amount',
            field=models.FloatField(),
        ),
    ]
