# Generated by Django 2.1.5 on 2022-04-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0014_auto_20220407_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
