# Generated by Django 2.1.5 on 2022-05-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0015_auto_20220420_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='sdesc',
        ),
    ]
