# Generated by Django 2.1.5 on 2022-04-04 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminmodule', '0013_auto_20220313_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(default='12345', max_length=50)),
                ('address', models.CharField(default='india', max_length=500)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('cid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminmodule.City')),
                ('sid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminmodule.State')),
            ],
        ),
    ]
