# Generated by Django 2.1.5 on 2022-04-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='user/userprofile.jpg', upload_to='user/'),
        ),
    ]
