# Generated by Django 2.1.5 on 2022-04-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totaldonation',
            field=models.FloatField(default=0),
        ),
    ]
