# Generated by Django 2.1.5 on 2022-02-10 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminmodule', '0003_auto_20220210_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(default='12345', max_length=50)),
                ('address', models.CharField(default='india', max_length=500)),
                ('cid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminmodule.City')),
                ('sid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminmodule.State')),
            ],
        ),
    ]
